schema: ./src/graphql/**/*.graphql
extensions:
  codegen:
    generates:
      ./generated-backend.ts:
        plugins:
          - typescript
          - typescript-resolvers
  diff:
    baseSchema: ./src/graphql/**/*.graphql
